services:

  localstack:
    container_name: localstack-todo
    image: localstack/localstack:latest-amd64
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/:/etc/localstack/init/ready.d/
