services:

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      DISABLE_CORS_CHECKS: 1
      DYNAMODB_SHARE_DB: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  setup-localstack:
    image: hashicorp/terraform
    depends_on:
      - localstack
    restart: no
    volumes:
      - ./terraform:/tmp/terraform
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566/
      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: yyy
    entrypoint: [ '/bin/sh', '-c', 'cd /tmp/terraform && terraform init && terraform apply -auto-approve' ]
